import './globals.css'
import type { Metadata } from 'next'
import { Fira_Code } from 'next/font/google'

const inter = Fira_Code({ subsets: ['latin'], weight: "400" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="uz">
      <body className={inter.className}>
        <p>Navbar</p>
        {children}
        <p>Footer</p>
        </body>
    </html>
  )
}
